#!/bin/sh
export PATH=$PATH:@CMAKE_RUNTIME_OUTPUT_DIRECTORY@:@CURRENT_FIXED_BIN_DIRS@
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:@CMAKE_LIBRARY_OUTPUT_DIRECTORY@:@CURRENT_FIXED_LIBRARY_DIRS@
@CURRENT_OUTPUT_NAME@ $*
#read -p "Press any key to continue"